docker-compose-yaml: docker-compose.yml

tasks:
  post-deploy:
    - run:
        name: Install a new Drupal from scratch
        command: cd web && drush si config_installer -y --account-name=admin --account-pass=admin install_configure_form.enable_update_status_module=NULL install_configure_form.enable_update_status_emails=NULL
        service: cli
    - run:
        name: drush cr
        command: cd web && drush -y cr
        service: cli